
insert into category(category_name, category_id) values('국립공원',1);
insert into category(category_name, category_id) values('멋진 수영장',2);
insert into category(category_name, category_id) values('초소형 주택',3);
insert into category(category_name, category_id) values('통나무집',4);
insert into category(category_name, category_id) values('개인실',5);
insert into category(category_name, category_id) values('최고의 전망',6);
insert into category(category_name, category_id) values('한옥',7);
insert into category(category_name, category_id) values('인기 급상승',8);
insert into category(category_name, category_id) values('료칸',9);
insert into category(category_name, category_id) values('해변 바로 앞',10);
insert into category(category_name, category_id) values('저택',11);
insert into category(category_name, category_id) values('한적한 시골',12);
insert into category(category_name, category_id) values('기상천외한 숙소',13);
insert into category(category_name, category_id) values('캠핑장',14);
insert into category(category_name, category_id) values('농장',15);
insert into category(category_name, category_id) values('캐슬',16);
insert into category(category_name, category_id) values('디자인',17);
insert into category(category_name, category_id) values('호수 근처',18);
insert into category(category_name, category_id) values('Luxe',19);
insert into category(category_name, category_id) values('스키',20);
insert into category(category_name, category_id) values('상징적 도시',21);
insert into category(category_name, category_id) values('신규',22);
insert into category(category_name, category_id) values('열대 지역',23);
insert into category(category_name, category_id) values('세상의 꼭대기',24);
insert into category(category_name, category_id) values('창작 공간',25);
insert into category(category_name, category_id) values('와인 농장',26);
insert into category(category_name, category_id) values('사막',27);
insert into category(category_name, category_id) values('컨테이너하우스',28);
insert into category(category_name, category_id) values('그랜드 피아노',29);
insert into category(category_name, category_id) values('속세를 벗어난 숙소',30);
insert into category(category_name, category_id) values('섬',31);
insert into category(category_name, category_id) values('키즈',32);
insert into category(category_name, category_id) values('B&amp;B',33);
insert into category(category_name, category_id) values('유서 깊은 주택',34);
insert into category(category_name, category_id) values('호숫가',35);
insert into category(category_name, category_id) values('골프장',36);
insert into category(category_name, category_id) values('복토 주택',37);
insert into category(category_name, category_id) values('북극',38);
insert into category(category_name, category_id) values('동굴',39);
insert into category(category_name, category_id) values('돔하우스',40);
insert into category(category_name, category_id) values('보트',41);
insert into category(category_name, category_id) values('전문가급 주방',42);
insert into category(category_name, category_id) values('헛간',43);
insert into category(category_name, category_id) values('A자형 주택',44);
insert into category(category_name, category_id) values('서핑',45);
insert into category(category_name, category_id) values('유르트',46);
insert into category(category_name, category_id) values('하우스보트',47);
insert into category(category_name, category_id) values('스키를 탄 채로 출입 가능',48);
insert into category(category_name, category_id) values('민수',49);
insert into category(category_name, category_id) values('마차',50);
insert into category(category_name, category_id) values('트리하우스',51);
insert into category(category_name, category_id) values('무장애',52);
insert into category(category_name, category_id) values('트룰로',53);
insert into category(category_name, category_id) values('캠핑카',54);
insert into category(category_name, category_id) values('키클라데스 주택',55);
insert into category(category_name, category_id) values('풍차',56);
insert into category(category_name, category_id) values('카사 파르티쿨라르',57);
insert into category(category_name, category_id) values('타워',58);
insert into category(category_name, category_id) values('담무소',59);
insert into category(category_name, category_id) values('리아드',60);
insert into category(category_name, category_id) values('해변 근처', 61);



insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c0a24c04-ce1f-490c-833f-987613930eca.jpg',1);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/3fb523a0-b622-4368-8142-b5e03df7549b.jpg',2);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/35919456-df89-4024-ad50-5fcb7a472df9.jpg',3);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/732edad8-3ae0-49a8-a451-29a8010dcc0c.jpg',4);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/eb7ba4c0-ea38-4cbb-9db6-bdcc8baad585.jpg',5);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/3b1eb541-46d9-4bef-abc4-c37d77e3c21b.jpg',6);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/51f5cf64-5821-400c-8033-8a10c7787d69.jpg',7);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/3726d94b-534a-42b8-bca0-a0304d912260.jpg',8);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/827c5623-d182-474a-823c-db3894490896.jpg',9);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/bcd1adc0-5cee-4d7a-85ec-f6730b0f8d0c.jpg',10);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/78ba8486-6ba6-4a43-a56d-f556189193da.jpg',11);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/6ad4bd95-f086-437d-97e3-14d12155ddfe.jpg',12);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c5a4f6fc-c92c-4ae8-87dd-57f1ff1b89a6.jpg',13);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/ca25c7f3-0d1f-432b-9efa-b9f5dc6d8770.jpg',14);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/aaa02c2d-9f0d-4c41-878a-68c12ec6c6bd.jpg',15);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/1b6a8b70-a3b6-48b5-88e1-2243d9172c06.jpg',16);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/50861fca-582c-4bcc-89d3-857fb7ca6528.jpg',17);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/a4634ca6-1407-4864-ab97-6e141967d782.jpg',18);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c8e2ed05-c666-47b6-99fc-4cb6edcde6b4.jpg',19);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c8bba3ed-34c0-464a-8e6e-27574d20e4d2.jpg',20);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/ed8b9e47-609b-44c2-9768-33e6a22eccb2.jpg',21);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c0fa9598-4e37-40f3-b734-4bd0e2377add.jpg',22);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/ee9e2a40-ffac-4db9-9080-b351efc3cfc4.jpg',23);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/248f85bf-e35e-4dc3-a9a1-e1dbff9a3db4.jpg',24);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/8a43b8c6-7eb4-421c-b3a9-1bd9fcb26622.jpg',25);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/60ff02ae-d4a2-4d18-a120-0dd274a95925.jpg',26);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/a6dd2bae-5fd0-4b28-b123-206783b5de1d.jpg',27);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/0ff9740e-52a2-4cd5-ae5a-94e1bfb560d6.jpg',28);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/8eccb972-4bd6-43c5-ac83-27822c0d3dcd.jpg',29);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/9a2ca4df-ee90-4063-b15d-0de7e4ce210a.jpg',30);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/8e507f16-4943-4be9-b707-59bd38d56309.jpg',31);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/f0c5ca0f-5aa0-4fe5-b38d-654264bacddf.jpg',32);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/5ed8f7c7-2e1f-43a8-9a39-4edfc81a3325.jpg',33);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/33dd714a-7b4a-4654-aaf0-f58ea887a688.jpg',34);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/677a041d-7264-4c45-bb72-52bff21eb6e8.jpg',35);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/6b639c8d-cf9b-41fb-91a0-91af9d7677cc.jpg',36);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/d7445031-62c4-46d0-91c3-4f29f9790f7a.jpg',37);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/8b44f770-7156-4c7b-b4d3-d92549c8652f.jpg',38);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/4221e293-4770-4ea8-a4fa-9972158d4004.jpg',39);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/89faf9ae-bbbc-4bc4-aecd-cc15bf36cbca.jpg',40);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/687a8682-68b3-4f21-8d71-3c3aef6c1110.jpg',41);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/ddd13204-a5ae-4532-898c-2e595b1bb15f.jpg',42);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/f60700bc-8ab5-424c-912b-6ef17abc479a.jpg',43);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/1d477273-96d6-4819-9bda-9085f809dad3.jpg',44);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/957f8022-dfd7-426c-99fd-77ed792f6d7a.jpg',45);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/4759a0a7-96a8-4dcd-9490-ed785af6df14.jpg',46);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c027ff1a-b89c-4331-ae04-f8dee1cdc287.jpg',47);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/757deeaa-c78f-488f-992b-d3b1ecc06fc9.jpg',48);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/48b55f09-f51c-4ff5-b2c6-7f6bd4d1e049.jpg',49);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/747b326c-cb8f-41cf-a7f9-809ab646e10c.jpg',50);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/4d4a4eba-c7e4-43eb-9ce2-95e1d200d10e.jpg',51);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/e22b0816-f0f3-42a0-a5db-e0f1fa93292b.jpg',52);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/33848f9e-8dd6-4777-b905-ed38342bacb9.jpg',53);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/31c1d523-cc46-45b3-957a-da76c30c85f9.jpg',54);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/e4b12c1b-409b-4cb6-a674-7c1284449f6e.jpg',55);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/5cdb8451-8f75-4c5f-a17d-33ee228e3db8.jpg',56);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/251c0635-cc91-4ef7-bb13-1084d5229446.jpg',57);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/d721318f-4752-417d-b4fa-77da3cbc3269.jpg',58);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/c9157d0a-98fe-4516-af81-44022118fbc7.jpg',59);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/7ff6e4a1-51b4-4671-bc9a-6f523f196c61.jpg',60);
insert into picture(url, picture_id) values('https://a0.muscache.com/pictures/10ce1091-c854-40f3-a2fb-defc2995bcaf.jpg',61);



insert into home(place, addr, price) values('Calaca', '필리핀','328224');
insert into home(place, addr, price) values('City of Naga', '필리핀','162799');
insert into home(place, addr, price) values('Gunnae-myeon', '한국','102820');
insert into home(place, addr, price) values('Tegallalang', '인도네시아','227221');
insert into home(place, addr, price) values('Kecamatan Kediri', '인도네시아','176939');
insert into home(place, addr, price) values('Toyooka', '일본','168624');
insert into home(place, addr, price) values('애월읍', '한국','276165');
insert into home(place, addr, price) values('Unisan', '필리핀','391243');
insert into home(place, addr, price) values('Wapato', '미국','243012');
insert into home(place, addr, price) values('우드스탁', '미국','248490');
insert into home(place, addr, price) values('Half Moon Bay', '미국','322693');
insert into home(place, addr, price) values('Wadi Rum', '요르단','107489');
insert into home(place, addr, price) values('조슈아 트리', '미국','504094');
insert into home(place, addr, price) values('Middelfart', '덴마크','85075');
insert into home(place, addr, price) values('모아브', '미국','373876');
insert into home(place, addr, price) values('Holbrook', '미국','86327');
insert into home(place, addr, price) values('마라케시', '모로코','271904');
insert into home(place, addr, price) values('Alberton', '미국','145497');
insert into home(place, addr, price) values('Wadi Rum Village', '요르단','31531');
insert into home(place, addr, price) values('Page', '미국','327554');
insert into home(place, addr, price) values('Page', '미국','179481');
insert into home(place, addr, price) values('콘월(Cornwall)', '영국','189825');
insert into home(place, addr, price) values('우드스탁', '미국','232319');
insert into home(place, addr, price) values('São Vicente', '포르투갈','66830');
insert into home(place, addr, price) values('Gunnae-myeon', '한국','102820');
insert into home(place, addr, price) values('NO', '노르웨이','184229');
insert into home(place, addr, price) values('엘 프라도(El Prado)', '미국','175398');
insert into home(place, addr, price) values('Beer Milka', '이스라엘','829991');
insert into home(place, addr, price) values('조슈아 트리', '미국','226646');
insert into home(place, addr, price) values('Villa de Juárez', '멕시코','448943');
insert into home(place, addr, price) values('Benton', '미국','229245');
insert into home(place, addr, price) values('Faraday', '캐나다','127459');
insert into home(place, addr, price) values('Husum', '독일','97735');
insert into home(place, addr, price) values('켄트(Kent)', '영국','2122585');
insert into home(place, addr, price) values('Bonfield', '캐나다','112076');
insert into home(place, addr, price) values('스톤 마운틴(Stone Mountain)', '미국','262837');
insert into home(place, addr, price) values('Sabóia', '포르투갈','61690');
insert into home(place, addr, price) values('벨', '미국','224465');
insert into home(place, addr, price) values('조슈아 트리', '미국','714920');
insert into home(place, addr, price) values('Townsend', '미국','441350');
insert into home(place, addr, price) values('Eumundi', '오스트레일리아','203769');
insert into home(place, addr, price) values('스톤 마운틴(Stone Mountain)', '미국','349449');
insert into home(place, addr, price) values('헌츠빌(Huntsville)', '미국','148591');
insert into home(place, addr, price) values('Cane Beds ', '미국','186392');
insert into home(place, addr, price) values('오스틴', '미국','472476');
insert into home(place, addr, price) values('Jackson', '미국','417187');
insert into home(place, addr, price) values('La Ciotat', '프랑스','387109');
insert into home(place, addr, price) values('Terlingua', '미국','150855');
insert into home(place, addr, price) values('Terlingua', '미국','164436');
insert into home(place, addr, price) values('Gunnae-myeon', '한국','157940');
insert into home(place, addr, price) values('Eumundi', '오스트레일리아','203769');
insert into home(place, addr, price) values('Mid Wales', '영국','257127');
insert into home(place, addr, price) values('매리언(Marion)', '미국','321036');
insert into home(place, addr, price) values('배스트롭', '미국','225738');
insert into home(place, addr, price) values('Upper Sturt', '오스트레일리아','144814');
insert into home(place, addr, price) values('Thermopolis', '미국','281794');
insert into home(place, addr, price) values('Atlanta ', '미국','377774');
insert into home(place, addr, price) values('New Cuyama', '미국','245077');
insert into home(place, addr, price) values('The Patch', '오스트레일리아','191899');
insert into home(place, addr, price) values('Mhamid', '모로코','24675');
insert into home(place, addr, price) values('El Nido', '필리핀','253565');
insert into home(place, addr, price) values('애월읍', '한국','259707');
insert into home(place, addr, price) values('West Java', '인도네시아','236689');
insert into home(place, addr, price) values('Kecamatan Bogor Timur', '인도네시아','568053');
insert into home(place, addr, price) values('구좌읍', '한국','113479');
insert into home(place, addr, price) values('相模原市', '일본','281710');
insert into home(place, addr, price) values('Shimonoseki', '일본','142419');
insert into home(place, addr, price) values('내쉬빌', '미국','110760');
insert into home(place, addr, price) values('Terlingua', '미국','187060');
insert into home(place, addr, price) values('Fernhurst', '영국','137609');
insert into home(place, addr, price) values('팔마 데 마요르카', '스페인','85283');
insert into home(place, addr, price) values('오악사카', '멕시코','21735');
insert into home(place, addr, price) values('뉴포트', '미국','143342');
insert into home(place, addr, price) values('말리부', '미국','516973');
insert into home(place, addr, price) values('İzmir', '터키','95133');
insert into home(place, addr, price) values('브런즈윅 헤즈', '오스트레일리아','102478');
insert into home(place, addr, price) values('Saint Petersburg', '미국','196685');
insert into home(place, addr, price) values('Clermont', '미국','204276');
insert into home(place, addr, price) values('Columbiana', '미국','134993');
insert into home(place, addr, price) values('링콘(Rincón)', '푸에르토리코','168335');
insert into home(place, addr, price) values('Kos', '그리스','74328');
insert into home(place, addr, price) values('Kajiado County', '케냐','137718');
insert into home(place, addr, price) values('Sylt', '독일','131538');
insert into home(place, addr, price) values('Murter', '크로아티아','431820');
insert into home(place, addr, price) values('Tilba Tilba', '오스트레일리아','185495');
insert into home(place, addr, price) values('Albinia', '이탈리아','77031');
insert into home(place, addr, price) values('Castiglione della Pescaia', '이탈리아','137845');
insert into home(place, addr, price) values('Craftsbury', '미국','196833');
insert into home(place, addr, price) values('Castissent', '스페인','97302');
insert into home(place, addr, price) values('Nanaimo', '캐나다','216819');
insert into home(place, addr, price) values('Paia', '미국','329634');
insert into home(place, addr, price) values('프린스타운(Princetown)', '오스트레일리아','202781');
insert into home(place, addr, price) values('Virgin', '미국','345288');
insert into home(place, addr, price) values('Hildale', '미국','142885');
insert into home(place, addr, price) values('Damascus', '미국','69579');
insert into home(place, addr, price) values('Elgin', '미국','205162');
insert into home(place, addr, price) values('Moffat', '미국','180107');
insert into home(place, addr, price) values('코니어스(Conyers)', '미국','144311');
insert into home(place, addr, price) values('Key Largo', '미국','369118');
insert into home(place, addr, price) values('Serooskerke', '네덜란드','53052');
insert into home(place, addr, price) values('Urbanización Famara', '스페인','143940');
insert into home(place, addr, price) values('Los Angeles County', '미국','217814');
insert into home(place, addr, price) values('Nazaré', '포르투갈','264609');
insert into home(place, addr, price) values('Eastsound', '미국','193058');
insert into home(place, addr, price) values('Corvallis', '미국','148971');
insert into home(place, addr, price) values('Lakeview', '미국','289506');
insert into home(place, addr, price) values('Lanvéoc', '프랑스','126758');
insert into home(place, addr, price) values('Manteo', '미국','222996');
insert into home(place, addr, price) values('Island Park', '미국','172562');
insert into home(place, addr, price) values('Margaree Forks', '캐나다','116663');
insert into home(place, addr, price) values('오스틴', '미국','115723');
insert into home(place, addr, price) values('Willow City', '미국','230593');
insert into home(place, addr, price) values('Loupiac', '프랑스','121668');
insert into home(place, addr, price) values('Arrawarra Headland', '오스트레일리아','147356');
insert into home(place, addr, price) values('Smithsburg', '미국','101072');
insert into home(place, addr, price) values('Eastsound', '미국','260878');
insert into home(place, addr, price) values('콜럼비아 폴스(Columbia Falls)', '미국','199009');
insert into home(place, addr, price) values('Franklin Township', '미국','765908');
insert into home(place, addr, price) values('Cohasset', '미국','588335');
insert into home(place, addr, price) values('Recoubeau-Jansac', '프랑스','127304');
insert into home(place, addr, price) values('Island Park', '미국','214712');
insert into home(place, addr, price) values('Vienna', '오스트리아','214876');
insert into home(place, addr, price) values('비스타(Vista)', '미국','163384');
insert into home(place, addr, price) values('Kingscote', '오스트레일리아','271692');
insert into home(place, addr, price) values('Loures', '포르투갈','197021');
insert into home(place, addr, price) values('Nathrop', '미국','132936');
insert into home(place, addr, price) values('Sabie', '남아프리카','53808');
insert into home(place, addr, price) values('Pagosa Springs', '미국','521857');
insert into home(place, addr, price) values('Riverside County', '미국','177430');
insert into home(place, addr, price) values('Pacific City', '미국','259858');
insert into home(place, addr, price) values('Saint-Martin-le-Mault', '프랑스','94288');
insert into home(place, addr, price) values('Talkeetna', '미국','71659');
insert into home(place, addr, price) values('Williams', '미국','463012');
insert into home(place, addr, price) values('Eidsvoll', '노르웨이','167281');
insert into home(place, addr, price) values('Paia', '미국','225299');
insert into home(place, addr, price) values('Stonecrest', '미국','174597');
insert into home(place, addr, price) values('Carrabelle', '미국','91088');
insert into home(place, addr, price) values('로즈버그(Roseburg)', '미국','32236');
insert into home(place, addr, price) values('Dahlonega', '미국','165925');
insert into home(place, addr, price) values('Ingelmunster', '벨기에','184553');
insert into home(place, addr, price) values('레이캬비크', '아이슬란드','75569');
insert into home(place, addr, price) values('캔자스시티', '미국','91118');
insert into home(place, addr, price) values('Sorico', '이탈리아','91299');
insert into home(place, addr, price) values('Setúbal', '포르투갈','46268');
insert into home(place, addr, price) values('아레시페(Arrecife)', '스페인','61690');
insert into home(place, addr, price) values('Végennes', '프랑스','93367');
insert into home(place, addr, price) values('아레시페(Arrecife)', '스페인','77110');
insert into home(place, addr, price) values('Gracefield', '캐나다','52023');
insert into home(place, addr, price) values('아레시페(Arrecife)', '스페인','53979');
insert into home(place, addr, price) values('Forks', '미국','182741');
insert into home(place, addr, price) values('Williams', '미국','144027');
insert into home(place, addr, price) values('알게로', '이탈리아','43183');
insert into home(place, addr, price) values('아레시페(Arrecife)', '스페인','78396');
insert into home(place, addr, price) values('새러소타', '미국','162307');
insert into home(place, addr, price) values('Pleasant Bay', '캐나다','189607');
insert into home(place, addr, price) values('Ambon', '프랑스','111819');
insert into home(place, addr, price) values('Leicester', '미국','101059');
insert into home(place, addr, price) values('Wootton Bridge ', '영국','119073');
insert into home(place, addr, price) values('Priest River', '미국','101222');
insert into home(place, addr, price) values('Nampa', '미국','80058');
insert into home(place, addr, price) values('더비(Derby)', '영국','47284');
insert into home(place, addr, price) values('홀루알로아(Holualoa)', '미국','159914');
insert into home(place, addr, price) values('Puntarenas Province', '코스타리카','119194');
insert into home(place, addr, price) values('오클랜드', '뉴질랜드','80102');
insert into home(place, addr, price) values('West Glacier', '미국','244326');
insert into home(place, addr, price) values('Brindisi', '이탈리아','54979');
insert into home(place, addr, price) values('Pompei', '이탈리아','53979');
insert into home(place, addr, price) values('테메큘라', '미국','300309');
insert into home(place, addr, price) values('Elizabethton', '미국','106594');
insert into home(place, addr, price) values('Alamosa', '미국','102873');
insert into home(place, addr, price) values('웨이브랜드(Waveland)', '미국','78690');
insert into home(place, addr, price) values('아레시페(Arrecife)', '스페인','93226');
insert into home(place, addr, price) values('Región de Murcia', '스페인','46267');
insert into home(place, addr, price) values('카마이오레', '이탈리아','38557');
insert into home(place, addr, price) values('네이플스', '미국','166718');
insert into home(place, addr, price) values('Hinton', '캐나다','288566');
insert into home(place, addr, price) values('Brooksville', '미국','155869');
insert into home(place, addr, price) values('Miller Lake', '캐나다','336301');
insert into home(place, addr, price) values('Stege', '덴마크','60430');
insert into home(place, addr, price) values('어퍼 말보로(Upper Marlboro)', '미국','100577');
insert into home(place, addr, price) values('상트페테르부르크(St Petersburg)', '미국','131547');
insert into home(place, addr, price) values('에사우이라', '모로코','64889');
insert into home(place, addr, price) values('Lake City', '미국','96160');
insert into home(place, addr, price) values('피닉스(Phoenix)', '미국','91677');
insert into home(place, addr, price) values('Waterton Park', '캐나다','173809');
insert into home(place, addr, price) values('De Koog', '네덜란드','164733');
insert into home(place, addr, price) values('La Boussac', '프랑스','111233');
insert into home(place, addr, price) values('Bredene', '벨기에','69709');
insert into home(place, addr, price) values('York', '캐나다','195243');
insert into home(place, addr, price) values('Hallbergmoos', '독일','61914');
insert into home(place, addr, price) values('Rizvanuša', '크로아티아','195862');
insert into home(place, addr, price) values('Mareil-sur-Loir', '프랑스','49357');
insert into home(place, addr, price) values('Letojanni', '이탈리아','21591');
insert into home(place, addr, price) values('Mohave Valley', '미국','67602');
insert into home(place, addr, price) values('콘월(Cornwall)', '영국','250117');
insert into home(place, addr, price) values('San Juan Bautista', '미국','221428');
insert into home(place, addr, price) values('모아브', '미국','248792');
insert into home(place, addr, price) values('Lagny-sur-Marne', '프랑스','50935');
insert into home(place, addr, price) values('Voorschoten', '네덜란드','55519');
insert into home(place, addr, price) values('아그드', '프랑스','42029');
insert into home(place, addr, price) values('산타페(Santa Fe)', '미국','93544');
insert into home(place, addr, price) values('Oostvoorne', '네덜란드','77109');
insert into home(place, addr, price) values('Nampa', '미국','81897');
insert into home(place, addr, price) values('몬로비아(Monrovia)', '미국','78416');
insert into home(place, addr, price) values('Forks', '미국','324949');
insert into home(place, addr, price) values('Freetown', '캐나다','111008');
insert into home(place, addr, price) values('Yreka', '미국','88817');
insert into home(place, addr, price) values('Santa Paula', '미국','173416');
insert into home(place, addr, price) values('Saint-Hilaire-de-Riez', '프랑스','95207');
insert into home(place, addr, price) values('Artignosc-sur-Verdon', '프랑스','138872');
insert into home(place, addr, price) values('Himarë', '알바니아','53979');
insert into home(place, addr, price) values('Tinn Austbygd', '노르웨이','118026');
insert into home(place, addr, price) values('Deer Lake', '캐나다','96615');
insert into home(place, addr, price) values('Lund', '캐나다','159199');
insert into home(place, addr, price) values('Axel', '네덜란드','111038');
insert into home(place, addr, price) values('San Cristobal', '미국','125965');
insert into home(place, addr, price) values('Puivert', '프랑스','101878');